image: "alpine:edge"

stages:
  - Prettier Linting
  - Build HTML

prettier:
  stage: Prettier Linting
  script:
    - apk add --no-cache npm
    - npx prettier --check src/*.md

html:
  stage: Build HTML
  script:
    - apk add --no-cache cargo zip
    - cargo install mdbook --no-default-features
    - mdbook build
    - zip -r book.zip book/
  artifacts:
    paths:
      - book.zip
    expire_in: 1 day
