[book]
authors = ["Jens Reidel", "Max Heymann", "Force#0154", "Cho#2417", "captainflame#8625", "Thesariya NJ#9008", "Jaebelle#6003", '"👹Don`t Me👹"#8858']
language = "en"
multilingual = false
src = "src"
title = "IdleRPG Guide"
